"""Generate deterministic living documentation for the Apple Pay demo."""

from __future__ import annotations

import argparse
import ast
import hashlib
import re
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
README = ROOT / "README.md"
WORKFLOW_DOC = ROOT / "docs" / "generated" / "integrated-ai-demo-quality-gates.md"
README_START = "<!-- AI-DEMO-DOCS:START -->"
README_END = "<!-- AI-DEMO-DOCS:END -->"
SOURCE_INPUTS = [
    ROOT / "src" / "payment" / "payment_processor.py",
    ROOT / "src" / "payment" / "apple_pay_payment_method.py",
    ROOT / "tests" / "payment" / "apple_pay.feature",
    ROOT / "tests" / "payment" / "test_apple_pay.py",
    ROOT / "docs" / "api" / "apple-pay-openapi.yaml",
    ROOT / "docs" / "tickets" / "TECH-DEBT-payment-module-security-fixes.md",
    ROOT / "tools" / "generate_workflow_report.py",
    ROOT / ".github" / "workflows" / "integrated-ai-demo-quality-gates.yml",
]


@dataclass(frozen=True)
class Scenario:
    kind: str
    title: str


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def source_digest() -> str:
    digest = hashlib.sha256()
    for path in SOURCE_INPUTS:
        digest.update(path.relative_to(ROOT).as_posix().encode("utf-8"))
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()[:16]


def extract_classes(path: Path) -> list[str]:
    tree = ast.parse(read_text(path))
    return [node.name for node in ast.walk(tree) if isinstance(node, ast.ClassDef)]


def extract_functions(path: Path) -> list[str]:
    tree = ast.parse(read_text(path))
    return [node.name for node in ast.walk(tree) if isinstance(node, ast.FunctionDef)]


def extract_scenarios() -> list[Scenario]:
    scenarios = []
    pattern = re.compile(r"^\s*(Scenario(?: Outline)?):\s+(.+?)\s*$")
    for line in read_text(ROOT / "tests" / "payment" / "apple_pay.feature").splitlines():
        match = pattern.match(line)
        if match:
            scenarios.append(Scenario(match.group(1), match.group(2)))
    return scenarios


def build_readme_section(digest: str, scenarios: list[Scenario]) -> str:
    scenario_titles = ", ".join(s.title for s in scenarios[:4])
    if len(scenarios) > 4:
        scenario_titles += f", plus {len(scenarios) - 4} more"
    return f"""{README_START}
## Integrated AI Workflow Quality Gates

This repository includes an end-to-end GitHub Actions demo that mirrors architecture discovery, technical debt assessment, test-first development, implementation validation, and API documentation generation.

| Gate | Evidence |
|---|---|
| Architecture discovery | Confirms PaymentProcessor strategy registration and ApplePayPaymentMethod extension points. |
| Technical debt guardrail | Requires the legacy security debt ticket while preventing new Apple Pay secret or raw-token logging regressions. |
| BDD test contract | Runs {len(scenarios)} Apple Pay scenarios covering happy path, validation, retries, timeout, and rollback. |
| API documentation | Validates docs/api/apple-pay-openapi.yaml for auth, schemas, examples, retry headers, and error responses. |
| Living README | This section is regenerated from source digest `{digest}` on every workflow run. |
| HTML execution report | Publishes a self-contained debugging report with gate results, file inventory, raw logs, and troubleshooting guidance. |

**Current Apple Pay scenario map:** {scenario_titles}.

Generated docs:
- [Integrated AI demo quality gates](docs/generated/integrated-ai-demo-quality-gates.md)
- [Apple Pay OpenAPI spec](docs/api/apple-pay-openapi.yaml)
- `reports/integrated-ai-workflow-report.html` as a workflow artifact after each Actions run

Source digest: `{digest}`
{README_END}"""


def build_workflow_doc(digest: str, scenarios: list[Scenario]) -> str:
    payment_classes = extract_classes(ROOT / "src" / "payment" / "payment_processor.py")
    apple_classes = extract_classes(ROOT / "src" / "payment" / "apple_pay_payment_method.py")
    functions = sorted(set(extract_functions(ROOT / "src" / "payment" / "apple_pay_payment_method.py")))
    scenario_rows = "\n".join(f"| {i} | {s.kind} | {s.title} |" for i, s in enumerate(scenarios, 1))
    watched = "\n".join(f"- `{p.relative_to(ROOT).as_posix()}`" for p in SOURCE_INPUTS)
    return f"""# Integrated AI Demo Quality Gates

This file is generated by `tools/generate_demo_docs.py`.

Source digest: `{digest}`

## Demo Story

The workflow validates architecture discovery, technical debt containment, BDD tests, implementation behavior, API documentation, living docs, and workflow evidence.

## Architecture Discovery Evidence

- `src/payment/payment_processor.py`: {", ".join(payment_classes)}
- `src/payment/apple_pay_payment_method.py`: {", ".join(apple_classes)}

Apple Pay functions: {", ".join(functions)}.

## BDD Acceptance Contract

| # | Type | Scenario |
|---|---|---|
{scenario_rows}

## Quality Gates

| Stage | Gate | What breaks the build |
|---|---|---|
| Architecture | Strategy-pattern contract | Missing core payment classes. |
| Technical debt | Known-risk containment | Missing tech-debt ticket, hardcoded Apple Pay secrets, or raw token logging. |
| Testing | BDD suite | Any failing pytest-bdd scenario. |
| API docs | OpenAPI contract | Missing endpoint, auth, schemas, examples, or retry metadata. |
| Evidence | HTML report | Missing execution summary, change summary, file inventory, troubleshooting guidance, or raw workflow logs. |

## Files Watched By The Digest

{watched}
"""


def insert_readme_section(base: str, section: str) -> str:
    if README_START in base and README_END in base:
        return re.sub(f"{re.escape(README_START)}.*?{re.escape(README_END)}", section, base, flags=re.S)
    return base.rstrip() + "\n\n" + section + "\n"


def build_artifacts() -> dict[Path, str]:
    digest = source_digest()
    scenarios = extract_scenarios()
    return {README: insert_readme_section(read_text(README), build_readme_section(digest, scenarios)), WORKFLOW_DOC: build_workflow_doc(digest, scenarios)}


def write_artifacts(artifacts: dict[Path, str]) -> list[Path]:
    changed = []
    for path, content in artifacts.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        normalized = content.rstrip() + "\n"
        if not path.exists() or read_text(path) != normalized:
            path.write_text(normalized, encoding="utf-8")
            changed.append(path)
    return changed


def check_artifacts(artifacts: dict[Path, str]) -> list[Path]:
    return [path for path, expected in artifacts.items() if not path.exists() or read_text(path) != expected.rstrip() + "\n"]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    missing = [path for path in SOURCE_INPUTS if not path.exists()]
    if missing:
        for path in missing:
            print(f"Missing source input: {path.relative_to(ROOT).as_posix()}", file=sys.stderr)
        return 2
    artifacts = build_artifacts()
    if args.check:
        stale = check_artifacts(artifacts)
        if stale:
            print("Generated documentation is stale:", file=sys.stderr)
            for path in stale:
                print(f"- {path.relative_to(ROOT).as_posix()}", file=sys.stderr)
            return 1
        print("Generated documentation is in sync.")
        return 0
    changed = write_artifacts(artifacts)
    if changed:
        print("Updated generated documentation:")
        for path in changed:
            print(f"- {path.relative_to(ROOT).as_posix()}")
    else:
        print("Generated documentation already up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
